// Labels inside the generated .docx / .pdf. The web UI has its own dictionary
// (Step 4); this one only covers what ends up in the documents.

export type DocLang = "zh" | "en";

export function docLang(value: unknown): DocLang {
  return value === "en" ? "en" : "zh";
}

const STRINGS = {
  zh: {
    minutesTitle: "會議紀錄",
    reportTitle: "逐字稿報告書",
    date: "日期",
    duration: "時長",
    attendees: "出席講者",
    source: "來源",
    summary: "摘要",
    transcript: "逐字稿",
    time: "時間",
    speaker: "講者",
    content: "內容",
    generatedBy: "由 Video Speed Reader 產生",
    noSummary: "（尚未產生摘要）",
    page: "頁",
  },
  en: {
    minutesTitle: "Meeting Minutes",
    reportTitle: "Transcript Report",
    date: "Date",
    duration: "Duration",
    attendees: "Speakers",
    source: "Source",
    summary: "Summary",
    transcript: "Transcript",
    time: "Time",
    speaker: "Speaker",
    content: "Content",
    generatedBy: "Generated by Video Speed Reader",
    noSummary: "(no summary generated)",
    page: "Page",
  },
} as const;

export type DocStrings = { [K in keyof (typeof STRINGS)["zh"]]: string };

export function strings(lang: DocLang): DocStrings {
  return STRINGS[lang];
}

export function formatDuration(seconds: number, lang: DocLang): string {
  const m = Math.max(1, Math.ceil(seconds / 60));
  if (lang === "zh") return m >= 60 ? `${Math.floor(m / 60)} 小時 ${m % 60} 分` : `${m} 分鐘`;
  return m >= 60 ? `${Math.floor(m / 60)} h ${m % 60} min` : `${m} min`;
}

export function formatDate(iso: string, lang: DocLang): string {
  const d = new Date(iso);
  return d.toLocaleDateString(lang === "zh" ? "zh-TW" : "en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    timeZone: "Asia/Taipei",
  });
}
